source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:hudl/podspecs.git'

platform :ios, '12.0'

project_path = '../RxErrors.xcodeproj'

target 'RxErrors' do
  project project_path
  use_frameworks!
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxSwiftExt'
end
